version: '3.9'
services:
    server:
        build: .
        ports:
            - '$PORT:80'
        volumes:
            - './.caddy:/caddy'
            - './.cache:/backend/.cache'
        env_file:
            - '.env'
        environment:
            - 'PUBLIC_DIR=/var/www/html'
        init: true