import { Award, AwardSentiment, AwardType } from '../types/common';

export const AWARDS: Award[] = [
    {
        type: AwardType.Kenny,
        name: 'Kenny',
        description: 'Most deaths',
        sentiment: AwardSentiment.Negative,
    },
    {
        type: AwardType.Buddhist,
        name: 'Buddhist',
        description: 'Lowest damage to champions',
        sentiment: AwardSentiment.Negative,
    },
    {
        type: AwardType.TreeHugger,
        name: 'Tree Hugger',
        description: 'Lowest siege damage',
        sentiment: AwardSentiment.Negative,
    },
    {
        type: AwardType.ThriftShopper,
        name: 'Thrift Shopper',
        description: 'Lowest value full build',
        sentiment: AwardSentiment.Negative,
    },
    {
        type: AwardType.UnderpantsGnome,
        name: 'Underpants Gnome',
        description: 'Highest kill participation',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.BavarianGod,
        name: 'Bavarian God',
        description: 'Highest total damage dealt / gold invested in items',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.ScaredyPants,
        name: 'Scaredy Pants',
        description: 'Lowest deaths',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.Bulwark,
        name: 'Bulwark',
        description: 'Most damage taken',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.Thicc,
        name: 'Thicc',
        description: 'Highest damage taken / deaths',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.CombatMedic,
        name: 'Combat Medic',
        description: 'Most damage healed',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.Dominator,
        name: 'Dominator',
        description: 'Most takedowns / deaths (KDA)',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.Protector,
        name: 'Protector',
        description: 'Most damage prevented',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.Finisher,
        name: 'Finisher',
        description: 'Most kills',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.PainBringer,
        name: 'Pain Bringer',
        description: 'Most damage to champions',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.SiegeMaster,
        name: 'Siege Master',
        description: 'Most siege damage',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.CreepLover,
        name: 'Creep Lover',
        description: 'Highest CS',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.CrowdController,
        name: 'Crowd Controller',
        description: 'Most CC',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.SoleSurvivor,
        name: 'Sole Survivor',
        description: 'The only player without deaths',
        sentiment: AwardSentiment.Neutral,
    },
    {
        type: AwardType.RichBitch,
        name: 'Rich Bitch',
        description: 'Highest amount of gold earned',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.AlQaeda,
        name: 'Al-Qaeda',
        description: 'Last hit on all structures',
        sentiment: AwardSentiment.Positive,
    },
    {
        type: AwardType.PressingIntensifies,
        name: 'Pressing Intensifies',
        description: 'Highest number of spells cast',
        sentiment: AwardSentiment.Neutral,
    },
];
